version: '3'
services:
  react:
    build:
      context: .
      dockerfile: react/Dockerfile
    container_name: react_container
    volumes:
     - ./:/usr/src/app
    command: sh -c "cd react/react-sample && yarn start"
    ports:
     - "3000:3000"
  go:
    build:
      context: .
      dockerfile: go/Dockerfile
    container_name: go_container
    ports:
      - 8000:8000
    tty: true
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  db:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    container_name: db_container
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB